version: '3.1'
services:
  apiservice:
    build:
      context: .
      dockerfile: DockerfileApi
    restart: always
    image: apijwt
    ports:
      - 4000:80

  robaDatos:
    build:
      context: .
      dockerfile: Dockerfilehttp
    restart: always
    image: http

  proxy:
    container_name: proxyProjecto
    image: nginx
    ports:
      - 80:80
    volumes:
      - .\nginx\default.conf:/etc/nginx/conf.d/default.conf
